language: cpp
dist: xenial

script:
  - if [ "$CHECK_CLANG_FORMAT" == "True" ]; then
      clang-format --version;
      .travis/check_clang_format.sh;
    else
      ./autogen.sh;
      ./configure $CONFIGURE;
      make;
      make ${TEST:-test};
    fi

matrix:
  include:

  # Job 0: Ensure clang-format was applied
  - env: CHECK_CLANG_FORMAT=True

  # Job 1: Linux native GCC
  - os: linux
    compiler: gcc
    env: V=1 ENABLE_CACHE_CLEANUP_TESTS=1
    addons:
      apt:
        packages:
        - elfutils
        - libzstd1-dev
        - libb2-dev

  # Job 2: Linux native Clang
  - os: linux
    compiler: clang
    env: V=1 ENABLE_CACHE_CLEANUP_TESTS=1
    addons:
      apt:
        packages:
        - elfutils
        - libzstd1-dev
        - libb2-dev

  allow_failures:
  # show only info, do not fail (yet) for clang-format
  - env: CHECK_CLANG_FORMAT=True
